version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "increase"
    groups:
      security-patches:
        update-types:
          - "patch"
      minor-and-major:
        update-types:
          - "minor"
          - "major"